# Generated by Django 5.2.6 on 2025-11-17 00:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_calories", models.IntegerField(default=0)),
                (
                    "total_protein",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "total_carbs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "total_fat",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=10,
                    ),
                ),
                ("menu_item_id", models.IntegerField()),
                ("menu_item_name", models.CharField(max_length=200)),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.25"))
                        ],
                    ),
                ),
                ("calories_per_serving", models.IntegerField()),
                (
                    "protein_per_serving",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "carbs_per_serving",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fat_per_serving",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("total_calories", models.IntegerField()),
                (
                    "total_protein",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "total_carbs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "total_fat",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("dining_hall", models.CharField(blank=True, max_length=50)),
                ("station_name", models.CharField(blank=True, max_length=200)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_items",
                        to="plans.dailymealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_type", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My Meal Plan", max_length=200)),
                ("description", models.TextField(blank=True)),
                ("week_start_date", models.DateField()),
                ("daily_calorie_goal", models.IntegerField(blank=True, null=True)),
                ("daily_protein_goal", models.IntegerField(blank=True, null=True)),
                ("daily_carbs_goal", models.IntegerField(blank=True, null=True)),
                ("daily_fat_goal", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start_date"],
                "unique_together": {("user", "week_start_date")},
            },
        ),
        migrations.AddField(
            model_name="dailymealplan",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_plans",
                to="plans.plan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymealplan",
            unique_together={("plan", "date")},
        ),
    ]
