# Generated by Django 5.2.11 on 2026-03-05 06:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="cholesterol_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="fiber_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="saturated_fat_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="sodium_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="sugar_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="total_cholesterol",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="total_fiber",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="total_saturated_fat",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="total_sodium",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="total_sugar",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="total_trans_fat",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="trans_fat_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
