# Generated by Django 5.2.11 on 2026-03-05 06:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_add_extended_nutrients_to_mealitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealitem",
            name="cholesterol_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="sodium_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="total_cholesterol",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="total_sodium",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
    ]
