# Generated by Django 5.2.11 on 2026-03-05 06:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_fix_sodium_cholesterol_max_digits"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymealplan",
            name="total_cholesterol",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="dailymealplan",
            name="total_fiber",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="dailymealplan",
            name="total_saturated_fat",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="dailymealplan",
            name="total_sodium",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="dailymealplan",
            name="total_sugar",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="dailymealplan",
            name="total_trans_fat",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
    ]
