# Generated by Django 5.2.11 on 2026-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_add_extended_nutrients_to_dailymealplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="daily_fiber_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="daily_sodium_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
