# Generated by Django 5.2.6 on 2025-09-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="day_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
