# Generated by Django 5.2.6 on 2025-09-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_day_day_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="period",
            old_name="type",
            new_name="name",
        ),
    ]
