# Generated by Django 5.2.6 on 2025-09-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_type_period_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="ingredients",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
    ]
