# Generated by Django 5.2.6 on 2025-09-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_menuitem_ingredients_delete_ingredient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nutritioninfo",
            old_name="carbs",
            new_name="total_carbohydrates",
        ),
        migrations.RenameField(
            model_name="nutritioninfo",
            old_name="sugar",
            new_name="total_sugars",
        ),
    ]
