# Generated by Django 5.2.6 on 2025-09-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_carbs_nutritioninfo_total_carbohydrates_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nutritioninfo",
            old_name="fiber",
            new_name="dietary_fiber",
        ),
        migrations.RenameField(
            model_name="nutritioninfo",
            old_name="unsaturated_fat",
            new_name="total_fat",
        ),
    ]
