# Generated by Django 5.2.6 on 2025-09-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_fiber_nutritioninfo_dietary_fiber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritioninfo",
            name="cholesterol",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
