# Generated by Django 5.2.6 on 2025-11-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_nutritioninfo_cholesterol"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritioninfo",
            name="serving_size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
