# Generated by Django 5.2.11 on 2026-03-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_default_calorie_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_vegetarian",
            field=models.BooleanField(default=False),
        ),
    ]
