# Generated by Django 5.2.6 on 2026-03-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_dietary_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("sedentary", "Sedentary"),
                    ("light", "Lightly Active"),
                    ("moderate", "Moderately Active"),
                    ("active", "Very Active"),
                    ("very_active", "Extremely Active"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("maintain", "Maintain Weight"),
                    ("lose", "Lose Weight"),
                    ("gain", "Gain Muscle"),
                ],
                default="maintain",
                max_length=20,
            ),
        ),
    ]
