# Generated by Django 4.2.9 on 2026-03-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_goal_type_activity_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_fiber_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_sodium_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
